### ISSUE TITLE
Please add trial note to F-Droid description

### ISSUE THREAD

**Issue by silmaril42** [TeamAmaze/AmazeFileUtilities#107]
On [F-Droid](https://f-droid.org/de/packages/com.amaze.fileutilities/) the description contains no information about this app being a trial version that has to be paid to use after 20 days.

Please add something to the description to avoid user disappointment. Maybe this sentence (copied from `README.md`) would suffice?

> Note: This app is trial based and requires a nominal donation to unlock full version.

Just to be clear:
I think it's absolutely OK to provide the app on your terms and to ask for donations!  
I'd just prefer this to be communicated in a more transparent way.

**Comment by VishalNehra** [comment]
I'm not sure where the fdroid description is picked up from. I thought it'd be picked from readme. @linsui please suggest how to update the fdroid description to be same as readme file?

**Comment by linsui** [comment]
It's from this file. https://github.com/TeamAmaze/AmazeFileUtilities/blob/main/app/src/main/play/listings/en-US/full-description.txt

**Comment by VishalNehra** [comment]
Ahh I didn't update that for quite some time and directly made changes on play store console. I'll update this file then. Thanks for pointing.

**Comment by VishalNehra** [comment]
I've updated the listing text, how does this get reflected on fdroid?

**Comment by VishnuSanal** [comment]
@VishalNehra Upon next release, the bot picks up the new metadata from the fastlane/ directory.

**Comment by ruinernin** [comment]
This should be removed from F-Droid, it's a non-free app. A "donation" to remove a trial limitation is not a donation, it is a purchase of a licence. It is even called a 'subscription' within the app.

**Comment by linsui** [comment]
Free as in free speech, not in free beer, right?

**Comment by linsui** [comment]
Free as in free speech, not in free beer, right?

**Comment by VishalNehra** [comment]
> This should be removed from F-Droid, it's a non-free app. A "donation" to remove a trial limitation is not a donation, it is a purchase of a licence. It is even called a 'subscription' within the app.

This is not the correct forum to discuss this so I'll just leave you with the following.

Please take some time and go through 'free software' definition of GNU. Let me quote it here since you haven't done so

```
“Free software” means software that respects users' freedom and community. Roughly, it means that the users have the freedom to run, copy, distribute, study, change and improve the software. Thus, “free software” is a matter of liberty, not price. To understand the concept, you should think of “free” as in “free speech,” not as in “free beer.” We sometimes call it “libre software,” borrowing the French or Spanish word for “free” as in freedom, to show we do not mean the software is gratis.

You may have paid money to get copies of a free program, or you may have obtained copies at no charge. But regardless of how you got your copies, you always have the freedom to copy and change the software, even to [sell copies](https://www.gnu.org/philosophy/selling.html).
```
[Ref](https://www.gnu.org/philosophy/free-sw.en.html)

You can connect to us directly through our [telegram channel](https://t.me/AmazeFileManager), we'll be happy to discuss the same.

**Comment by licaon-kter** [comment]
Do add a note about the NonFreeNet antifeature in https://github.com/TeamAmaze/AmazeFileUtilities/blob/main/app/src/main/play/listings/en-US/full-description.txt to explain why does it need to connect to Google continuously and why it needs location and connects to Google/whatever for Transfers.

ref: https://gitlab.com/fdroid/fdroiddata/-/issues/2987#note_1386232119

**Comment by VishalNehra** [comment]
> Do add a note about the NonFreeNet antifeature in https://github.com/TeamAmaze/AmazeFileUtilities/blob/main/app/src/main/play/listings/en-US/full-description.txt to explain why does it need to connect to Google continuously and why it needs location and connects to Google/whatever for Transfers.
> 
> ref: https://gitlab.com/fdroid/fdroiddata/-/issues/2987#note_1386232119

It doesn't connect to Google for transfers. It's connecting to our backend to validate the trial period. 
Location permission is needed for [WifiP2P android APIs](https://developer.android.com/training/connect-devices-wirelessly/wifi-direct) to detect nearby devices and transfer the data.

**Comment by licaon-kter** [comment]
I see connections to `8.8.8.8` at the app start, aka Google. My Android can resolve DNS just fine, no need to bypass my system.

**Comment by VishalNehra** [comment]
> I see connections to `8.8.8.8` at the app start, aka Google. My Android can resolve DNS just fine, no need to bypass my system.

We're validating the trial period at app startup by connecting to our backend. It's using 8.8.8.8 to resolve the cloud function that's deployed on Google Cloud probably by their internal load balancer. 
Please let me know how is that a problem?

**Comment by licaon-kter** [comment]
It's not a _problem_, it's just a _reason_ to add the antifeature. :shrug:

**Comment by VishalNehra** [comment]
> It's not a _problem_, it's just a _reason_ to add the antifeature. 🤷
> 
> You can add that info to the Description, _"antifeature, nonfreenet, connects to our google hosted servers for license validation, blahblah"_

I'm just trying to understand what is required to solve the issue here. You're focused on marking our app anti-feature (which is fine as it's your job to do that). 
I would appreciate it if you help me understand what I can do to resolve this. 
If hosting environment is an issue, do you have a suggestion that's compliant with fdroid's FLOSS policies?

**Comment by licaon-kter** [comment]
I've said https://gitlab.com/fdroid/fdroiddata/-/issues/2987#note_1386441473

Maybe try to post only in one place so this discussion is not split :)

**Comment by VishalNehra** [comment]
> @VishalNehra with this app now being listed at F-Droid.org, am I assuming correctly you still want me to keep it in my repo (as Amaze FileManager)? Else it would be due to removal here now :wink:

Yes I want to keep the repo with IzzyDroid, thanks for checking! 🙂
