### ISSUE TITLE
readme conflicts with GPL and itself

### ISSUE THREAD

**Issue by iamsirsammy** [TeamAmaze/AmazeFileUtilities#113]
This projects is clearly licensed under the unmodified GPL 3, but lies to you about what you can legally do with the project in the readme:
```
Amaze File Utilities is licenced under [GPLv3](https://teamamaze.xyz/license-agreement-utilities) and anyone wanting to use it (as a base for your own project or even use some of its parts or features) has to adhere to this license completely. Make sure that you are aware of all the licensing terms before creating your own project based on Amaze Utilities.

Here some important points to keep in mind, as to how we handle licensing:

    You cannot simply rename our app, strip it of all credit and upload it anywhere as your own, be this with or without monetization.

    You have to make changes in terms of design, features, etc before publishing it anywhere. Changing app name, package name and logo is not enough.

    You are required to give us full credits for any work you may be using from us.

    We will ALWAYS use all our legal options, if you do not strictly adhere to these licencing terms.

    Copyright (C) 2021-2022 Arpit Khurana [arpitkh96@gmail.com](mailto:arpitkh96@gmail.com) Copyright (C) 2021-2022 Vishal Nehra [vishalmeham2@gmail.com](mailto:vishalmeham2@gmail.com) Copyright (C) 2021-2022 Emmanuel Messulam [emmanuelbendavid@gmail.com](mailto:emmanuelbendavid@gmail.com) Copyright (C) 2021-2022 Raymond Lai This file is part of Amaze File Utilities. Amaze File Utilities is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
```
Given the license of this project, it is completely legal to make a new version that just removes payment and keeps everything else the same, publish the app under a different name logo, or neglect giving any credit, as long as we still include the GPL. If you didn't want that, you should have picked a different license.

Please change the readme to more accurately reflect the chosen license.

**Comment by VishalNehra** [comment]
1. No where it says you cannot remove payment, and upload it anywhere **at all** You can do so following the GPL v3 license, and by following the platform policies where you're trying to distribute it (see point 3).
2. Including the license (and original author's name) in the modified and publicly available source code is in itself giving credit to the authors. If you give explicit credits within the user facing app or not is upto your ethics as a developer.
3. On top of that, many platforms such as Google Play Store, doesn't allow impersonation of other apps, so if you decide to publish your modified app on play store without significant changes in design and icons, we'll have a legal basis to claim impersonation (will modify the readme to include this). This ofcourse includes adding your own ads, monetization, adding or removing existing payment methods (with or without failing to follow the GPL v3 license).

I don't see see any _lies_ anywhere, the readme stands corrected. If you're having any issues in understanding, please feel free to open a discussion or contact us on telegram at https://t.me/AmazeFileManager

**Comment by iamsirsammy** [comment]
So to be clear, you are legally allowed to modify the software to remove payment, provided you provide a copy of the GPL and source code, as allowed by the GPL?

**Comment by iamsirsammy** [comment]
So to be clear, you are legally allowed to modify the software to remove payment (even if not recommended), provided you provide a copy of the GPL and source code, as allowed by the GPL? This is not what I read the readme as.

**Comment by VishalNehra** [comment]
> So to be clear, you are legally allowed to modify the software to remove payment (even if not recommended), provided you provide a copy of the GPL and source code, as allowed by the GPL? This is not what I read the readme as.

That is true, you're allowed to do that, and it isn't *not recommended* otherwise I wouldn't have made it open source under GPL v3. I'd appreciate if you (or anyone) goes ahead and remove the payment and use it for themselves and publish the source code. After all we're taking *donations* - it's upto you to donate or not.
However, you're not to distribute your modified app on Play Store or any such platforms which will violate their policies as it'll be impersonation of our app, forcing us to use legal means to get it removed. 
Hence the content in the readme. I'll update the readme and make this more clear.
