### ISSUE TITLE
Sd card, Otg support 

### ISSUE THREAD

**Issue by AdityaMishra135** [TeamAmaze/AmazeFileUtilities#128]
Load file from sd card, Otg etc

**Comment by VishnuSanal** [comment]
@AdityaMishra135 please provide more details on the issue you're facing.

**Comment by AdityaMishra135** [comment]
Sd card not detect. Sd card details not showing.

**Comment by VishnuSanal** [comment]
> Sd card not detect. Sd card details not showing.

please verify that you have downloaded Amaze from the official sources.

 Play Store
https://play.google.com/store/apps/details?id=com.amaze.filemanager

FDroid
https://apt.izzysoft.de/fdroid/index/apk/com.amaze.filemanager

AFH
https://www.androidfilehost.com/?w=files&flid=73967

GitHub
https://github.com/TeamAmaze/AmazeFileManager/releases


... also, is it that the SD card is being detected on other file manages & not Amaze?
