### ISSUE TITLE
file details option

### ISSUE THREAD

**Issue by nutpantz** [TeamAmaze/AmazeFileUtilities#137]
Right now the file details are just the filename for everything listed. 
It would be very helpful if the file path was listed also or at least an option in settings.

**Comment by VishalNehra** [comment]
Which screen are you talking about?

**Comment by nutpantz** [comment]
Pretty much every screen does not give the file path. Just the filename.

**Comment by VishalNehra** [comment]
This is fixed with new version. You should be able to see paths now, when listed in listview instead of grid view.
