### ISSUE TITLE
One-off error in `ReviewAnalysisAdapter`

### ISSUE THREAD

**Issue by seelchen** [TeamAmaze/AmazeFileUtilities#151]
At the top of the analysis review view the number of items is shown. However, it always has an one-off error because of [these lines](https://github.com/TeamAmaze/AmazeFileUtilities/blob/main/app/src/main/java/com/amaze/fileutilities/home_page/ui/analyse/ReviewAnalysisAdapter.kt#L60-L62) in the `ReviewAnalysisAdapter`, which add an `EMPTY_LAST_ITEM` if the list is not empty.

I am not sure why this `EMPTY_LAST_ITEM` has to be added, but I think that counting it as a item is quite confusing since the item itself not visible to the user. It should be at least subtracted when displaying the number of items. Or maybe the condition is wrong and was meant to check if the list is empty?

![one-off-error](https://github.com/TeamAmaze/AmazeFileUtilities/assets/74261221/96de73c1-63ad-40b3-bd28-14c7756fc374)

**Comment by VishalNehra** [comment]
I thought I fixed it, EMPTY_LAST_ITEM is added because some analysis are still being performed so we show a loading spinner at the end of the list for user to be aware that we're still processing that analysis.  Yea, maybe we need to subtract 1 from the number shown on top.
Eg:

**Comment by seelchen** [comment]
Ah, I see! There is the [`getOnlyItemsCount`](https://github.com/TeamAmaze/AmazeFileUtilities/blob/main/app/src/main/java/com/amaze/fileutilities/home_page/ui/analyse/ReviewAnalysisAdapter.kt#L114) method which probably was meant to fix this, but it still returns the one-off size.

**Comment by VishalNehra** [comment]
Right, so maybe do a -1 only for ReviewAnalysisAdapter implementation of getOnlyItemsCount.
