### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by licaon-kter** [TeamAmaze/AmazeFileUtilities#93]
You know what I mean ;)

**Comment by linsui** [comment]
It uses a pdf viewer

https://github.com/TeamAmaze/AmazeFileUtilities/blob/455ac17c48600c44c6b194a953e587b9517fa297/app/build.gradle#L248

which depends on pdfium

https://github.com/barteksc/AndroidPdfViewer/blob/d243b39377f19c3eae41e227067da254ebbf731b/android-pdf-viewer/build.gradle#L41

which is insecure. See https://divestos.org/misc/appsec.txt and https://github.com/SimpleMobileTools/Simple-File-Manager/issues/619. Ping @SkewedZeppelin
The opencv lib seems to be a package of the official opencv.

https://github.com/TeamAmaze/AmazeFileUtilities/blob/455ac17c48600c44c6b194a953e587b9517fa297/app/build.gradle#L270

There is no related source code in https://github.com/QuickBirdEng/opencv-android.

**Comment by VishalNehra** [comment]
Will work this on priority.

**Comment by smith901** [comment]
Take this mess and scammy Amaze File Manager off of F-Droid. This type of behavior is for the Play/App/Samsung Store.

**Comment by VishalNehra** [comment]
@linsui small update here, I've fixed the issues mentioned above and will soon merge them with master. However another issue with our project here is we're using a bunch of api tokens to make a few API calls (eg loading open subtitles for video player). We can't keep this public. Is there any way we can pass these onto fdroid build without making them public?

**Comment by licaon-kter** [comment]
No, there are no secrets.

Also, you do know that API keys can just be extracted from the APKs anyway, right?

**Comment by VishalNehra** [comment]
> No, there are no secrets.
> 
> Also, you do know that API keys can just be extracted from the APKs anyway, right?

Please see if there's a way. Gitlab allows injecting secrets when fdroid build triggers, shouldn't it be possible? 
We're obfuscating the apk it'll be difficult to extract the keys, even if it can be done doesn't mean we'll publish our api keys in a public repo.

**Comment by linsui** [comment]
You can leave the api key empty and ask the users to provide their own key. We don't build the prodution apk with GitLab CI and it's our policy to make sure all the source code is public available.

**Comment by VishalNehra** [comment]
> You can leave the api key empty and ask the users to provide their own key. We don't build the prodution apk with GitLab CI and it's our policy to make sure all the source code is public available.

Sure thanks for confirming. I'll see either to disable the features or adding a debug key which will limit the feature itself.
But I was expecting fdroid to provide a way, it's a pretty common usecase, and the source code is open source it's just the api keys which need to be secret for obvious reasons.

**Comment by licaon-kter** [comment]
> We're obfuscating the apk 

Maybe it's a good idea to not do that for F-Droid, imho

**Comment by linsui** [comment]
No, we don't have a size limit. Izzy has less resource so they have to limit the size.

**Comment by licaon-kter** [comment]
> Why so?
Why bother? What are you trying to hide exactly?

**Comment by VishalNehra** [comment]
> > Why so?
> 
> Why bother? What are you trying to hide exactly?

Right now my biggest concern is app size, since we're using large binaries such as opencv / mupdf, relying on obfuscation is our best chance to decrease app size. Not to mention it also removes any unused piece of code / resource while building. I don't see a reason not to obfuscate when our entire source code is open, that's why I asked.

**Comment by VishalNehra** [comment]
Our builds should start passing now. Can you try building main branch for `fdroid` flavour @linsui

**Comment by VishalNehra** [comment]
Available on fdroid now
https://f-droid.org/packages/com.amaze.fileutilities/
