### ISSUE TITLE
The "view all" button is unresponsive

### ISSUE THREAD

**Issue by yephny** [TeamAmaze/AmazeFileUtilities#95]
"View all" in the "Analyse" tab does nothing. Location access is denied, internet access is blocked with iptables.

Android 10, LineageOS.

**Comment by VishalNehra** [comment]
Yea the button is unresponsive for now. You can click anywhere else on that button apart from clean and it'll ooen up the analysis. Will fix the button as well.

**Comment by VishalNehra** [comment]
fixed with v1.72
